.\" Kai's Manpage Generator
.
.TH "ISYS" "1" "September 2021" "" ""
.
.SH "NAME"
\fBisys\fR \- The ISys Programming language interpreter
.
.SH "SYNOPSIS"
\fBisys\fR \fIoptions\fR
.
.SH "DESCRIPTION"
ISys is a language originally oriented around building scalable, Make\-Like programming language to build real\-time build systems\. ISys is implemented in D\.
.
.P
ISys has a very strict typing rule\.
.
.SS "strings"
Strings are presented in two forms, 1: Word 2: Dynamic String\.
.
.P
You can use comments in strings by using the "**" operator and making sure to not use any spaces\.
.
.P
Comments can be used without hassle in the programming language\.

.P
The comment operator is "**"\.
.
.P
Comment generation can be found in the igc\.d file\.
.
.SS "if statements"
If statement syntax is like so\.
.
.P
\fBIF (FUNCTION) DO (STAT)\fR
.
.P
Where STAT is an expression such as PRINT, Execute, etc\|\.\|\.\|\.
.
.P
IF statement source code can be found in the iif\.d file\.
.
.SS "keywords"
Keywords currently are
.
.IP "\[ci]" 4
PRINT
.
.IP "\[ci]" 4
EXECUTE
.
.IP "" 0
.
.P
Keywords give the interpreter basic things to do in your code\.
.
.SS "errors"
D errors could be any of the following
.
.IP "\[ci]" 4
Range Exceptions
.
.IP "\[ci]" 4
NULL Exceptions
.
.IP "\[ci]" 4
Any D exception
.
.IP "\[ci]" 4
Syntatic error
.
.IP "" 0
.
.SS "options"
\fB\-\-repl, \-r\fR
.
.P
Runs the REPL (read, eval, print, loop)
.
.P
You can run commands line by line in the REPL\. use \fB\-f\fR for files\.
.
.P
(BOOL | FLAG)
.
.P
\fB\-\-file, \-f\fR
.
.P
Runs a ISys Formatted File\. either ending in \.is, or \.isys\.
.
.P
(STRING)
.
.P
\fB\-\-verbose, \-v\fR
.
.P
Prints information about the operations and functions run\.
.
.P
(BOOL | FLAG)
.
.P
\fB\-\-startup=FILE, \-s\fR
.
.P
Runs a startup file before doing any operations\.
.
.P
(STRING | FILE)
