#!/usr/bin/python3

"""

IANA: ISys Analyzer
Gives you simple tips such as Isolations, Deprecations, and Statements.

"""

import pathlib
import argparse
from sys import flags

parser = argparse.ArgumentParser("iana")

parser.add_argument("FILE", type=str)
parser.add_argument("-warnbleed", default=True, action='store_false')
parser.add_argument("-warnisolated", default=True, action='store_false')
parser.add_argument("-warnperf", default=True, action="store_false")
args = parser.parse_args()

file = open(args.FILE, "r")

if pathlib.Path(args.FILE).exists():
    llist = file.readlines()
    i = 1
    for line in llist:
        if line == "":
            continue;
        if line[len(line)-1] != ";" and line[0] != "(":
            if args.warnbleed:
                print("Warning: (Line " + str(i) + ") did not use ';' at the end of statement. expect some bleeding through statements.")
                print("Wrong token: " + line[len(line)-1])
        i += 1
else:
    print("unable to analyze: file not found")
